language: node_js
node-js:
-11.10.0
cache: npm

install: 
  npm install ci

script: 
 npm run build  

deploy:
  provider: pages
  skip-cleanup: true
  github-token: f873dd1a161d8e933a832dbbb30c41bc23b18cd6
  local_dir: build
  on:
    branch: master