language: node_js

install: 
  - npm install ci

script:
  - npm build 

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  on:
    branch: master