language: node_js
cache: npm

install: 
  - npm install ci

script:
  - npm deploy 

after_success:
  - git config --global user.name "MariaJoseLind"
  - git config --global user.email "mariajoselind97@gmail.com"
  - git remote rm origin
  - git remote add origin https://MariaJoseLind:${GH_TOKEN}@github.com/IngSW-prueba/
  - npm run deploy
