language: node_js
cache: npm

install: 
  - npm install ci

script: 
 - npm build  

deploy:
  provider: pages
  skip-cleanup: true
  github-token: f873dd1a161d8e933a832dbbb30c41bc23b18cd6
  local_dir: build
  on:
    branch: master