language: node_js
node-js:
-11.10.0
cache: npm

install: 
  -npm install

script: 
 -npm run test
 -npm run build  

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB-TOKEN
  on:
    branch: master